#!/bin/bash
set -euo pipefail

# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.

. /usr/sbin/so-common

cat << EOF

so-checkin will run a full salt highstate to apply all salt states. If a highstate is already running, this request will be queued and so it may pause for a few minutes before you see any more output. For more information about so-checkin and salt, please see:
https://securityonion.net/docs/salt

EOF

if ! systemctl is-active --quiet salt-minion; then
    echo "ERROR: salt-minion service is not running." >&2
    exit 1
fi

salt-call state.highstate -l info queue=True || exit $?
