#!/bin/bash
set -euo pipefail
#
# Copyright Security Onion Solutions LLC and/or licensed to Security Onion Solutions LLC under one
# or more contributor license agreements. Licensed under the Elastic License 2.0 as shown at
# https://securityonion.net/license; you may not use this file except in compliance with the
# Elastic License 2.0.



. /usr/sbin/so-common

echo "$banner"
printf "Starting local Salt Minion...\n"
echo "$banner"

systemctl start salt-minion || { echo "ERROR: Failed to start salt-minion (exit $?)" >&2; exit 1; }
systemctl status salt-minion
